name: Create Release

on:
  push:
    tags: ["*"]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to get tag message

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Get tag message
        id: tag-message
        run: |
          TAG_NAME=${{ github.ref_name }}
          git tag -l $TAG_NAME --format="## %(contents:subject)

          %(contents:body)" > body.md

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body_path: body.md
          files: |
            main.js
            manifest.json
